import './globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'

// defining the font family here
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
  variable: '--font-poppins',
});

// defining the metadata here
export const metadata: Metadata = {
  title: 'Sticky Notes || Made with love by MJ Aumi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // rendering the layout of the web application here
  return (
    <html lang='en' className={`${poppins.variable}`}>
      <body className='font-poppins'>
        {children}
      </body>
    </html>
  )
}
